SELECT *
FROM FACILITIES;
SELECT NAME, ELEVATION, FACILITYID
FROM FLOORS;


SELECT 
    CONCAT(CONCAT(NAME,' | '),ID)"SPACENAME",
    ROUND(NETAREA*1.2,1) "+20PCT",
    TO_CHAR(CREATEDAT,'YYYY-MM-DD'),'HOLA'
FROM SPACES
WHERE ROUND(NETAREA*1.2,1)>=12 
    AND ROUND(NETAREA*1.2,1)<=50
    OR TO_CHAR(CREATEDAT,'YYYY')='2018'
ORDER BY 2 ASC, 3 DESC;

DESC COMPONENT_TYPES;

SELECT ID, NAME, MODELNUMBER
FROM COMPONENT_TYPES
WHERE ID =30 OR ID=60 OR ID=90;

SELECT ID, NAME, MODELNUMBER
FROM COMPONENT_TYPES
WHERE ID NOT IN (30,60,90);

SELECT COUNT(DISTINCT INSTALLATEDON),
    COUNT(INSTALLATEDON),
    COUNT(ID),
    COUNT(*),
    COUNT(WARRANTYSTARTON),
    COUNT(DISTINCT WARRANTYSTARTON)
FROM COMPONENTS
WHERE FACILITYID=2
ORDER BY 1;



SELECT 
    SUM(DISTINCT NETAREA),
    SUM(NETAREA),
    ROUND(AVG(NETAREA),2),
    MAX(NETAREA),
    MIN(NETAREA),
    COUNT(*)
FROM SPACES;

SELECT 
    NAME,
    NETAREA
FROM SPACES
ORDER BY 2 DESC;

SELECT 
    NAME
FROM SPACES
WHERE NETAREA = (SELECT MAX (NETAREA) FROM SPACES);