SELECT NAME
FROM SPACES
WHERE FLOORID=1;

SELECT NAME, ID
FROM FLOORS
WHERE FACILITYID=1;

SELECT NAME
FROM SPACES
WHERE FLOORID=1 IN
    (SELECT ID
    FROM FLOORS
    WHERE FACILITYID=1);

SELECT count(*), COUNT(NAME), COUNT (DISTINCT FLOORID)
FROM SPACES;

SELECT SPACES.NAME
FROM FLOORS, SPACES
WHERE FLOORS.ID = SPACES.FLOORID
AND FLOORID=1
AND FACILITYID=1; 

SELECT NAME, MODELNUMBER
FROM COMPONENT_TYPES
WHERE ID=60;

SELECT NAME, INSTALLATEDON
FROM COMPONENTS
WHERE SPACEID=60
ORDER BY INSTALLATEDON DESC;

SELECT INSTALLATEDON
FROM COMPONENTS
WHERE FACILITYID=1
ORDER BY INSTALLATEDON DESC;

SELECT id, assetidentifier, externalidentifier, serialnumber, name
FROM COMPONENTS
WHERE spaceid between 10 and 27
ORDER BY spaceid desc;

SELECT id, assetidentifier, externalidentifier, serialnumber, name
FROM COMPONENTS
WHERE spaceid >= 10 and spaceid <= 27
ORDER BY spaceid desc;

SELECT id, assetidentifier, externalidentifier, serialnumber, name
FROM COMPONENTS
WHERE facilityid=1
ORDER BY assetidentifier desc;

SELECT assetidentifier
FROM COMPONENTS
WHERE spaceid = 21
ORDER BY assetidentifier desc;

SELECT installatedon, spaceid
FROM COMPONENTS
WHERE spaceid in (10,12,16,19)
ORDER BY installatedon desc;

select name, volume
from spaces
where volume > 90
and floorid=1
order by volume desc;

select name, volume
from spaces
where volume between 6 and 9
and floorid=1;

SELECT NAME, ASSETIDENTIFIER, SERIALNUMBER, SPACEID, FACILITYID
FROM COMPONENTS
WHERE FACILITYID=1
AND SPACEID IS NULL;

SELECT COUNT (*), COUNT (SPACEID)
FROM COMPONENTS
WHERE FACILITYID=1;

SELECT NAME, ASSETIDENTIFIER, SERIALNUMBER
FROM COMPONENTS
WHERE FACILITYID=1
AND SERIALNUMBER IS NOT NULL;

SELECT NAME, ASSETIDENTIFIER, SERIALNUMBER
FROM COMPONENTS
WHERE FACILITYID=1
AND SERIALNUMBER IS NULL;

SELECT NAME
FROM SPACES
WHERE NAME LIKE 'A%' 
AND FLOORID=1;

SELECT NAME
FROM SPACES
WHERE NAME LIKE '_s%'
AND FLOORID=1;

SELECT NAME
FROM component_types
WHERE facilityid=1
AND name like '%con%'
and (expectedlife is null
or  warrantydescription is null);

SELECT NAME, VOLUME,
    CASE
        WHEN VOLUME<10 THEN 'BAJO'
        WHEN VOLUME>=10 AND VOLUME <=1000 THEN 'MEDIO'
        ELSE 'ALTO'
    END "ALIAS"
FROM SPACES;

SELECT NAME, INSTALLATEDON, WARRANTYSTARTON
FROM COMPONENTS
WHERE FACILITYID=1
AND WARRANTYSTARTON IS NOT NULL;

SELECT COUNT(*), COUNT(WARRANTYSTARTON)
FROM COMPONENTS
WHERE FACILITYID=1;

SELECT COUNT (NAME)
    FROM SPACES
    WHERE NAME not like 'Aula%' AND FLOORID=1;

SELECT NAME
FROM component_types
WHERE warrantydurationparts IS NOT NULL
AND FACILITYID=1;

SELECT NAME
FROM component_types
WHERE replacementcost IS NULL
AND FACILITYID=1;

SELECT NAME
    FROM COMPONENT_TYPES
    WHERE FACILITYID=1
    AND NAME LIKE '%a_%' escape 'a';